<div class="msg-attachment">
    <img class="msg-attachment-icon" src="<?php echoh($assetFetcher->getLink("attachment.svg")) ?>" />
    <div class="msg-attachment-inner">
        <a href="<?php
            echoh(
                $assetFetcher->getLink(
                    $config['assets']['mapTestingLogs']['attachments']['subPath'] . $component->id . $component->extension
                )
            ) ?>" download>
            <?php echoh($component->basename) ?><?php echoh($component->extension) ?>
        </a>
        <div class="msg-attachment-filesize">
            <?php echoh($component->filesize) ?> <?php echoh($component->filesizeUnits) ?>
        </div>
    </div>
    <a href="<?php
        echoh(
            $assetFetcher->getLink(
                $config['assets']['mapTestingLogs']['attachments']['subPath'] . $component->id . $component->extension
            )
        ) ?>" download>
        <svg viewBox="0 0 24 24" class="download-button" name="Download" with="24px" height="24px">
            <g fill="none" fill-rule="evenodd">
                <path d="M0 0h24v24H0z"></path>
                <path class="fill" fill="currentColor" d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z"></path>
            </g>
        </svg>
    </a>
</div>
