<a class="image-wrap" href="<?php
    echoh(
        $assetFetcher->getLink(
            $config['assets']['mapTestingLogs']['attachments']['subPath'] . $component->id . $component->extension
        )
    ) ?>">
    <img class="msg-image" src="<?php
        echoh(
            $assetFetcher->getLink(
                $config['assets']['mapTestingLogs']['attachments']['subPath'] . $component->id . $component->extension
            )
        ) ?>" />
</a>
