<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <link
            rel="stylesheet"
            type="text/css"
            href="<?= $assetFetcher->getLink("app.css") ?>">
        <title><?= $log->getName() ?></title>
    </head>
    <body>
        <div class="container">
            <nav class="log-list">
                <h4 class="log-list-heading">Log list</h4>
                <ul>
                <?php foreach ($logList as $logItem): ?>
                        <li class="log-list-item<?=
                            $logItem->getName() == $log->getName() ? ' active' : ''
                        ?>">
                            <span class="channel-marker">#</span>
                            <a class="channel-name" href="<?= $router->pathFor(
                                'show.name',
                                ['name' => $logItem->getName()]
                                )?>"><?= $logItem->getName() ?>
                            </a>
                        </li>
                <?php endforeach;?>
                </ul>
            </nav>
            <div class="log-container">
                <?= $log->getHtml() ?>
            </div>
        </div>
    </body>
</html>
