<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <link
            rel="stylesheet"
            type="text/css"
            href="<?php echoh($assetFetcher->getLink("app.css")) ?>">
        <title>#<?php echoh($log->name) ?></title>
    </head>
    <body>
        <div class="container">
            <div class="log-list-container">
                <?php echo($viewRenderer->fetch('partials/list.phtml', [
                    'log' => $log,
                    'logList' => $logList
                ])) ?>
            </div>
            <div class="log-container">
                <?php echo($viewRenderer->fetch('partials/show.phtml', [
                    'log' => $log
                ])) ?>
            </div>
        </div>
        <script src="<?php echoh($assetFetcher->getLink("app.js")) ?>" charset="utf-8"></script>
    </body>
</html>
